global:
  __name: master

  firstname: Cedric
  lastname: Haase
  email: cedric@sineband.de


i3config:
  __templates:
    - .i3/config
    - .i3/autostart.sh

  #applications
  browser: firefox

  commands:
    - compton

  bar:
    position: top
    status_command: ~/.i3status.sh
    colors:
      background: '#000000'
      statusline: '#FFFFAA'
      focused_workspace:
        border: '#AACC33'
        background: '#88AA11'
        text: '#ffffff'
      active_workspace:
        border: '#333333'
        background: '#5f676a'
        text: '#ffffff'
      inactive_workspace:
        border: '#333333'
        background: '#222222'
        text: '#888888'
      urgent_workspace:
        border: '#2f343a'
        background: '#900000'
        text: '#ffffff'
      binding_mode:
        border: '#2f343a'
        background: '#900000'
        text: '#ffffff'

  colors:
    client.focused:
      border: '#AACC33'
      background: '#222222'
      text: '#AACC66'
      indicator: '#000000'
      child_border: '#222222'
    client.focused_inactive:
      border: '#446644'
      background: '#222222'
      text: '#779966'
      indicator: '#000000'
      child_border: '#222222'
    client.unfocused:
      border: '#AACCBB'
      background: '#222222'
      text: '#666666'
      indicator: '#000000'
      child_border: '#222222'
    client.urgent:
      border:
      background:
      text:
      indicator:
      child_border:
    client.placeholder:
      border:
      background:
      text:
      indicator:
      child_border:
    client.background:
      border: '#000000'

i3status:
  __templates:
    - .config/i3status/config
    - .i3status.sh

  # items to display in i3status
  items:
    - uptime
    - network
    - load
    - time
#    - disk
#    - battery
#    - dhcp
#    - vpn
#    - mpd


vimrc:
  __templates: [.vimrc]


xinitrc:
  __templates: [.xinitrc]


Xmodmap:
  __templates: [.Xmodmap]

  map:
    9: [Escape]
    10: [exclam,      1]
    11: [at,          2]
    12: [numbersign,  3]
    13: [dollar,      4]
    14: [percent,     5]
    15: [asciicircum, 6]
    16: [ampersand,   7]
    17: [asterisk,    8]
    18: [parenleft,   9]
    19: [parenright,  0]
    20: [underscore, minus]
    21: [equal, plus]
    22: [BackSpace, BackSpace]
    23: [ISO_Left_Tab, Tab]
    24: [Q, q]
    25: [W, w]
    26: [E, e]
    27: [R, r]
    28: [T, t]
    29: [Y, y]
    30: [U, u]
    31: [I, i]
    32: [O, o]
    33: [P, p]
    34: [braceleft, bracketleft]
    35: [braceright, bracketright]
    36: [Return]
    38: [A, a]
    39: [S, s]
    40: [D, d]
    41: [F, f]
    42: [G, g]
    43: [H, h]
    44: [J, j]
    45: [K, k]
    46: [L, l]
    47: [colon, semicolon]
    48: [quotedbl, apostrophe]
    49: [asciitilde, grave]
    50: [Shift_L]
    51: [bar, backslash]
    52: [Z, z]
    53: [X, x]
    54: [C, c]
    55: [V, v]
    56: [B, b]
    57: [N, n]
    58: [M, m]
    59: [less, comma]
    60: [greater, period]
    61: [question, slash]
    62: [Shift_R]
    63: [KP_Multiply, KP_Multiply] # keypad *
    64: [Meta_L, Alt_L]
    65: [space]
    66: [Control_L]
    67: [F1, F1]
    68: [F2, F2]
    69: [F3, F3]
    70: [F4, F4]
    71: [F5, F5]
    72: [F6, F6]
    73: [F7, F7]
    74: [F8, F8]
    75: [F9, F9]
    76: [F10, F10]

    108: [Multi_key] # Alt_R

    191: [XF86Tools] # F13


Xresources:
  __templates: [.Xresources]

  perl_ext_common:
    - tabbed


zshrc:
  __templates: [.zshrc]

  theme: wedisagree
  plugins: [git]

  disable_auto_update: true
  disable_untracked_files_dirty: true


gitconfig:
  __templates: [.gitconfig]
